Repository Culturale/culturale-frontend, pull requests merged in 2023-05, with the labels that each got.

#17 Refactor Login flow to follow architecture
  App.tsx
  app/application/application.ts
  app/application/controllers/controller.interface.ts
  app/application/controllers/controller.ts
  app/application/controllers/driver-controller/driver-controller.interface.ts
  app/application/controllers/driver-controller/driver-controller.test.ts
  app/application/controllers/driver-controller/driver-controller.ts
  app/application/controllers/driver-controller/index.ts
  app/application/controllers/index.ts
  app/application/controllers/user-controller/__snapshots__/driver-controller.test.ts.snap
  app/application/controllers/user-controller/index.ts
  app/application/controllers/user-controller/user-controller.interface.ts
  app/application/controllers/user-controller/user-controller.test.ts
  app/application/controllers/user-controller/user-controller.ts
  app/application/use-cases/login/login.ts
  app/config/env.ts
  app/infrastructure/api/api.interface.ts
  app/infrastructure/api/api.mock.ts
  app/infrastructure/api/api.ts
  app/infrastructure/infrastructure.ts
  app/navigation/index.ts
  app/navigation/root-navigator.tsx
  app/navigation/root-params.ts
  app/navigation/tab-navigator.tsx
  app/views/index.ts
  app/views/login-screen/index.ts
  app/views/login-screen/login-screen.props.ts
  app/views/login-screen/login-screen.tsx
  app/views/login.tsx
Labels: :wrench: Refactor

#32 Setup i18n
  app/components/text/index.ts
  app/components/text/text.props.ts
  app/components/text/text.tsx
  app/i18n/i18n.ts
  app/i18n/index.ts
  app/i18n/translate.ts
  app/i18n/translations/en.json
  app/i18n/translations/es.json
Labels: :floppy_disk: Setup

#30 Retrieve Events from culturale-server and store them in EventController
  app/application/controllers/event-controller/event-controller.ts
  app/components/event/event.tsx
  app/components/event/index.ts
  app/components/index.tsx
  app/components/navbar/index.ts
  app/components/navbar/navbar.tsx
  app/domain/entities/event/event.ts
  app/domain/entities/user/user.interface.ts
  app/domain/entities/user/user.ts
  app/domain/factories/chat.factory.ts
  app/domain/factories/chat.json
  app/domain/factories/event.factory.test.ts
  app/domain/factories/event.factory.ts
  app/domain/factories/event.json
  app/domain/factories/message.json
  app/domain/factories/user.factory.ts
  app/domain/factories/user.json
  app/infrastructure/api/api.interface.ts
  app/infrastructure/api/api.ts
  app/infrastructure/api/open-api.yml
  app/infrastructure/api/schema.ts
  app/navigation/root-params.ts
  app/navigation/tab-navigator.tsx
  app/views/HomeScreen.tsx
  app/views/home-screen/home-screen.props.ts
  app/views/home-screen/home-screen.styles.ts
  app/views/home-screen/home-screen.tsx
  app/views/home-screen/index.ts
  app/views/index.ts
  ios/Podfile
  ios/Podfile.lock
  ios/culturalefront.xcodeproj/project.pbxproj
  ios/culturalefront.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/culturalefront/Info.plist
  package.json
Labels: :star: Feature

#34 Create profile screen and edit profile screen
  app/application/application.ts
  app/application/controllers/event-controller/event-controller.ts
  app/application/controllers/user-controller/user-controller.interface.ts
  app/application/controllers/user-controller/user-controller.ts
  app/application/use-cases/login/login.ts
  app/application/use-cases/signup/signup.ts
  app/components/index.tsx
  app/components/navbar/index.ts
  app/components/navbar/navbar.tsx
  app/domain/factories/event.factory.ts
  app/infrastructure/api/api.interface.ts
  app/infrastructure/api/api.ts
  app/infrastructure/api/open-api.yml
  app/infrastructure/api/schema.ts
  app/navigation/root-navigator.tsx
  app/navigation/root-params.ts
  app/navigation/tab-navigator.tsx
  app/views/HomeScreen.tsx
  app/views/ProfileScreen.tsx
  app/views/editProfile-screen/editProfile-screen.props.ts
  app/views/editProfile-screen/editProfile-screen.styles.ts
  app/views/editProfile-screen/editProfile-screen.tsx
  app/views/editProfile-screen/index.ts
  app/views/home-screen/home-screen.tsx
  app/views/index.ts
  app/views/profile-screen/index.ts
  app/views/profile-screen/profile-screen.styles.ts
  app/views/profile-screen/profile-screen.tsx
  assets/card-logo.png
  assets/config-logo.png
  assets/friend-logo.png
Labels: :star: Feature

#40 Add translations for profile and event screen
  app/components/event/event.tsx
  app/i18n/translations/en.json
  app/i18n/translations/es.json
  app/views/EventsScreen.tsx
  app/views/HomeScreen.tsx
  app/views/event-screen/event-screen.styles.ts
  app/views/event-screen/event-screen.tsx
  app/views/home-screen/home-screen.tsx
  app/views/profile-screen/profile-screen.tsx
Labels: :wrench: Refactor

#37 Upload photo to aws
  android/app/src/main/AndroidManifest.xml
  app/application/controllers/user-controller/user-controller.interface.ts
  app/application/controllers/user-controller/user-controller.ts
  app/components/event/event.tsx
  app/components/evento/evento.tsx
  app/components/navbar/navbar.tsx
  app/config/env.ts
  app/domain/entities/event/event.interface.ts
  app/domain/entities/event/event.ts
  app/i18n/translations/en.json
  app/i18n/translations/es.json
  app/infrastructure/api/api.ts
  app/infrastructure/infrastructure.interface.ts
  app/infrastructure/infrastructure.ts
  app/infrastructure/services/uploadPhoto/index.ts
  app/infrastructure/services/uploadPhoto/s3.interface.ts
  app/infrastructure/services/uploadPhoto/s3.ts
  app/views/editProfile-screen/editProfile-screen.styles.ts
  app/views/editProfile-screen/editProfile-screen.tsx
  app/views/event-screen/event-screen.styles.ts
  app/views/event-screen/event-screen.tsx
  app/views/home-screen/home-screen.tsx
  app/views/profile-screen/profile-screen.tsx
  ios/culturalefront/AppDelegate.mm
  ios/culturalefront/Info.plist
  package.json
  yarn.lock
Labels: :star: Feature
